### ISSUE TITLE
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor of shape [3,3,1024,2048] and type float

### ISSUE THREAD

**Issue by Ludoboii** [deepfakes/faceswap-playground#174]
## Expected behavior

The script should start training after being given the two input directories and leaving all settings to default (except for the verbose and preview options, which are enabled). I also tried running it with LowMem model.

## Actual behavior

I get the following error: [https://pastebin.com/bQvH80ww](https://pastebin.com/bQvH80ww). I believe it's because I don't have enough VRAM (it's running on my laptop's GTX 840M with 2GB memory), but I don't know how to lower VRAM usage.

## Steps to reproduce

Ran `python3 faceswap.py train -A ./data/siri -B ./data/meb -m ~/faceswap/models/ -p -v` while in the faceswap directory

## Other relevant information
- **Operating system and version:** elementary OS 0.4.1 Loki, built on "Ubuntu 16.04.3 LTS", Linux 4.13.0-43-generic
- **Python version:** 3.5.2
- **Faceswap version:** Latest commit 049a4e5
- **Faceswap method:** GPU
- **Other related issues:** #13 #21

**Comment by bryanlyon** [comment]
2gb or 3gb cards are not supported.  4gb cards can use lowmem 6gb+ cards can use original.

Unfortunately you cannot run faceswap on your card.  You will have to upgrade to a system capable of running a 4gb+ card.

**Comment by iperov** [comment]
@Ludoboii 
LowMem and batch-size 2 should work.
I suggest you to try DeepFaceLab, it has 2GB model for 64

**Comment by xielongze** [comment]
You can try -bs 2 or bs-4. I'm training with a 4gb card with original and it works fine.

**Comment by chn-lee-yumi** [comment]
I tried `-t lightweight -bs 2` on 950M 2G, also OOM. It seems no way to run it on 2GB vram devices.

**Comment by torzdf** [comment]
@chn-lee-yumi Lighweight has been tested working at 1.6GB with Memory Saving Gradients and Ping Pong enabled, No guarantee (it depends what else is using your gpu), but it is possible

**Comment by chn-lee-yumi** [comment]
@torzdf Thanks! I missed Ping Pong option. It can run well now with batch size 24. (32 will OOM)
